name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Generate changelog
      id: changelog
      run: echo "CHANGELOG=Release ${{ github.ref_name }} - Package improvements and bug fixes" >> $GITHUB_OUTPUT

    - name: Create Release
      id: create_release
      run: |
        gh release create ${{ github.ref_name }} \
          --title "Release ${{ github.ref_name }}" \
          --notes "${{ steps.changelog.outputs.CHANGELOG }}" \
          --draft=false \
          ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') && '--prerelease' || '' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Create source distribution
      run: |
        python -m pip install --upgrade pip build
        python -m build --sdist
        
        # Create a zip file for easy download
        zip -r dbf-to-csv-converter-${{ github.ref_name }}.zip . \
          -x "*.git*" "*__pycache__*" "*.pyc" "*/.*" "build/*" "dist/*" "*.egg-info/*" \
          "DAT_COVER*" "tests/__pycache__*" "SETUP.md"
        
    - name: Upload Release Assets
      run: |
        gh release upload ${{ github.ref_name }} ./dbf-to-csv-converter-${{ github.ref_name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}